project_id = "qroqygbculbfqkbinqmp"

[functions.driver-login]
verify_jwt = false

[functions.create-user-account]
verify_jwt = false

[functions.create-demo-account]
verify_jwt = false

[functions.reset-database]
verify_jwt = false

[functions.setup-rls]
verify_jwt = false

[functions.auth-check-email]
verify_jwt = false

[functions.driver-update-status]
verify_jwt = true

[functions.get-google-maps-key]
verify_jwt = false

[functions.driver-update-course-status]
verify_jwt = true

[functions.driver-courses]
verify_jwt = true

[functions.driver-get-notifications]
verify_jwt = true

[functions.driver-update-location]
verify_jwt = true
