project_id = "qroqygbculbfqkbinqmp"

[functions.driver-login]
verify_jwt = false

[functions.driver-signup]
verify_jwt = false

[functions.setup-database]
verify_jwt = false

[functions.driver-update-status]
verify_jwt = true
