project_id = "qroqygbculbfqkbinqmp"

[functions.cleanup-driver-accounts]
verify_jwt = false

[functions.admin-delete-driver-complete]
verify_jwt = true

[functions.driver-login]
verify_jwt = false

[functions.create-user-account]
verify_jwt = false

[functions.auth-check-email]
verify_jwt = false

[functions.admin-approve-driver]
verify_jwt = true

[functions.driver-update-status]
verify_jwt = true

[functions.get-google-maps-key]
verify_jwt = true

[functions.driver-update-course-status]
verify_jwt = true

[functions.driver-courses]
verify_jwt = true

[functions.driver-get-notifications]
verify_jwt = true

[functions.driver-update-location]
verify_jwt = true

[functions.driver-update-profile]
verify_jwt = true
